export const APPLY_STORAGE_FILTER = 'APPLY_STORAGE_FILTER';
export const APPLY_RAM_FILTER = 'APPLY_RAM_FILTER';
export const APPLY_LOCATION_FILTER = 'APPLY_LOCATION_FILTER';
export const APPLY_HARDDISK_FILTER = 'APPLY_HARDDISK_FILTER';
export const REMOVE_FILTERS = 'REMOVE_FILTERS';
export const REQUEST_SERVERS = 'REQUEST_SERVERS';
export const RECEIVE_SERVERS = 'RECEIVE_SERVERS';
